var express = require('express');
var router = express.Router();
const User = require('../models/user');
const Vote = require('../models/vote');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const secretKey = process.env.SECRET_KEY || 'changeme';
const mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;
const debug = require('debug')('demo:users');


/* GET users listing. */
router.get('/', function (req, res, next) {
  User.find().sort('username').exec(function (err, users) {
    if (err) {
      return next(err);
    }
    res.send(users);
  });
});
router.get('/:id',loadUserFromParamsMiddleware, function (req, res, next) {
  res.send(req.user);
});
router.get('/:id/votes', loadUserFromParamsMiddleware, function(req,res,next){
  Vote.find({userId : req.user.id}).sort('-voteDate').exec(function (err, votes) {
    if (err) {
      return next(err);
    }
    res.send(votes);
  });
})  

/**
 * @api {post} /api/users Create a user
 * @apiName CreateUser
 * @apiGroup User
 * @apiVersion 1.0.0
 * @apiDescription Register a new user.
 *
 * @apiUse UserInRequestBody
 * @apiUse UserInResponseBody
 * @apiUse UserValidationError
 * @apiSuccess (Response body) {String} id A unique identifier for the user generated by the server
 *
 * @apiExample Example
 *     POST /api/users HTTP/1.1
 *     Content-Type: application/json
 *
 *     {
 *       "username": "TreyParker",
 *       "password": "301",
 *     }
 *
 * @apiSuccessExample 201 Created
 *     HTTP/1.1 201 Created
 *     Content-Type: application/json
 *     Location: https://sedes666.herokuapp.com/api/users/58b2926f5e1def0123e97281
 *
 *     {
 *       "id": "58b2926f5e1def0123e97281",
 *       "username": "TreyParker",
 *       "password": "$2a$07$hndQIDW9dAPAZMRdyp5Cg.IHk1B0p/bNFHXGBntbXsvIktFWkX1L.",
 *       "registrationDate": "2019-11-9T15:20:56.468Z",
 *       "__v":0
 *     }
 */

/* POST new user */
router.post('/', function (req, res, next) {
  //encrypt the password

  const plainPassword = req.body.password;
  const saltRounds = 10;
  bcrypt.hash(plainPassword, saltRounds, function (err, hashedPassword) {
    if (err) {
      return next(err);
    }

    // Create a new document from the JSON in the request body
    const newUser = new User(req.body);
    newUser.password = hashedPassword;
    // Save that document
    newUser.save(function (err, savedUser) {
      if (err) {
        return next(err);
      }
      // Send the saved document in the response
      console.log(`Welcome ${savedUser.username}`);
      res.send(savedUser);
    });
  });
});

/* LOGIN user */
router.post('/login', function (req, res, next) {
  User.findOne({ username: req.body.username }).exec(function (err, user) {
    if (err) {
      return next(err);
    } else if (!user) {
      return res.sendStatus(401);
      
    }
    bcrypt.compare(req.body.password, user.password, function (err, valid) {
      if (err) {
        return next(err);
      } else if (!valid) {
        return res.sendStatus(401);
      }
       // Generate a valid JWT which expires in 7 days.
       const exp = (new Date().getTime() + 7 * 24 * 3600 * 1000) / 1000;
       const claims = { sub: user._id.toString(), exp: exp };
       jwt.sign(claims, secretKey, function(err, token) {
         if (err) { return next(err); }
         res.send({ token: token }); // Send the token to the client.

          // Login is valid...
      //res.send(`Welcome ${user.username}!`);
    });
  });
});
});
/************************/
/* DELETE a user */
router.delete('/:id', function(req, res, next) {
  const id = req.params.id;
  User.deleteOne({ _id: id}, function (err, deleteUser) {
    if (err){ 
      return next(err);
    }
  res.send(`User ${id} has been deleted ;)`)
});
});
/************************/
/* PATCH a user */
router.patch('/:id', loadUserFromParamsMiddleware, function (req, res, next) {
  const plainPassword = req.body.password;
  const saltRounds = 10;
  bcrypt.hash(plainPassword, saltRounds, function (err, hashedPassword) {
    if (err) {
      return next(err);
    }
    req.user.password = hashedPassword;
  req.user.save(function (err, savedUser) {
    if (err) {
      return next(err);
    }

    debug(`Updated user "${savedUser.id}"`);
    res.send(savedUser);
  });
});
});

///////// 
function loadUserFromParamsMiddleware(req, res, next) {

  const userId = req.params.id;
  if (!ObjectId.isValid(userId)) {
    return userNotFound(res, userId);
  }

  let query = User.findById(userId)

  query.exec(function (err, user) {
    if (err) {
      return next(err);
    } else if (!user) {
      return userNotFound(res, userId);
    }

    req.user = user;
    next();
  });
}
function userNotFound(res, userId) {
  return res.status(404).type('text').send(`No user found with ID ${userId}`);
}

module.exports = router;
/**
 * @apiDefine UserInRequestBody
 * @apiParam (Request body) {String{3..50}} username The name of the user (unique)
 * @apiParam (Request body) {String{3..50}} password The secret pass of the suser
 */

/**
 * @apiDefine UserInResponseBody
 * @apiSuccess (Response body) {String} id The unique identifier of the user 
 * @apiSuccess (Response body) {String} username The name of the user (unique)
 * @apiSuccess (Response body) {String} password The secret pass of the user
 * @apiSuccess (Response body) {String} registrationDate The registration date of the user
 */

/**
 * @apiDefine UserValidationError
 *
 * @apiError {Object} 422/UnprocessableEntity Some of the user's properties are invalid
 *
 * @apiErrorExample {json} 422 Unprocessable Entity
 *     HTTP/1.1 422 Unprocessable Entity
 *     Content-Type: application/json
 *
 *     {
 *       "message": "user validation failed",
 *       "errors": {
 *         "username": {
 *           "kind": "minlength",
 *           "message": "Path `username` (`0`) is shorter than the minimum allowed length (3).",
 *           "name": "ValidatorError",
 *           "path": "username",
 *           "properties": {
 *             "message": "Path `{PATH}` (`{VALUE}`) is shorter than the minimum allowed length (3).",
 *             "minlength": 3,
 *             "path": "username",
 *             "type": "minlength",
 *             "value": "0"
 *           },
 *           "value": "0"
 *         }
 *       }
 *     }
 */